run:
  skip-dirs:
    - (^|/)bin($|/)
    - (^|/)examples($|/)
linters:
  enable:
    - asciicheck
    - asasalint
    - bidichk
    - bodyclose
    - contextcheck
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - exhaustive
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - interfacebloat
    - gosec
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - prealloc
    - promlinter
    - revive
    - rowserrcheck
    - exportloopref
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
    - gofumpt
linters-settings:
  funlen:
    statements: 50
  golint:
    min-confidence: 0.6
issues:
  exclude:
    - pkg/generated
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - maligned
        - noctx
        - scopelint
        - bodyclose
        - lll
        - goconst
        - gocognit
        - gocyclo
        - dupl
        - staticcheck
